# Generated by Django 3.2 on 2023-03-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('inquiry', models.TextField()),
                ('pending_reply', models.BooleanField(default=True)),
                ('marked_as_done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Customer Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InternalCommunicationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('related_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_message', to='inquiry.customerinquiry')),
            ],
        ),
    ]
